### ISSUE TITLE
Why is the cert-manager-operator for Red Hat not AllNamespaces

### ISSUE THREAD

**Issue by bitscuit** [openshift/cert-manager-operator#148] opened 2023-09-20 15:38 UTC
During tech preview, I was able to install cert-manager-operator in AllNamespaces mode. When was this support removed and why?

The CNCF cert-manager-operator is only installable in AllNamespaces mode, so why does the Red Hat one deviate from this?

![image](https://github.com/openshift/cert-manager-operator/assets/14062475/cf26f7aa-e3de-4bdb-aabe-e98950b354b8)

Additionally, cert-manager is a cluster wide service, and there is a limitation that there cannot be 2 active cert-manager-controllers on a cluster simultaneously since cert-manager never implemented this functionality properly https://github.com/cert-manager/cert-manager/issues/2525.

So with Red Hat cert-manager not restricting the install mode to only AllNamespaces, isn't there a risk that different users on a cluster accidentally install Red Hat cert-manager multiple times, leading to multiple active cert-manager-controllers?

**Comment by leifmadsen** [comment] 2023-11-17 04:07
I actually have run into this today. When you install in multiple namespaces, the Deployment.app for the operator conflicts, and is constantly updating.

![image](https://github.com/openshift/cert-manager-operator/assets/768751/e649a14c-c680-4c9b-89d9-f3a37a16d406)

**Comment by leifmadsen** [comment] 2024-03-18 02:45
While it seems most currently-developed Operators are moving to AllNamespaces mode, it is quite disruptive to change anything like this mid-channel version.  Documenting why this namespace method was used could be useful, but otherwise I'm happy to see this close.

**Comment by mikekaczmarski** [comment] 2024-04-11 18:13
The controller deployed by RH Cert Manager operator has cluster-wide permissions and visibility, as does the upstream CNCF/Jetstack Cert-Manager on which this is based.
Not installing the Cert-Manager in AllNamespaces mode does not change this.  Allowing installation in anything but AllNamespaces mode is misleading.  This is the essence of the bug

**Comment by mikekaczmarski** [comment] 2024-04-11 18:36
On further review of this, I believe that the desire on behalf of Red Hat was to install the operator in a namespace other than openshift-operators even though it is cluster scoped (essentially AllNamespace Mode).  Taking the default, the operator is installed in the cert-manager-operator namespace with its deployed resources running in the cert-manager namespace.   So this operator's payload does indeed have cluster scoped visibility and control (look at its clusterrolebindings).
The issue is in the OperatorHub dialog misrepresentation that installing Cert-Manager in a named namespace implies that it only watches and controls its CRs in that installed namespace.  Regardless of where its installed, it is essentially running in AllNamespace mode.

The OperatorHub DIalog is just WRONG with respect to this operator/payload.  

In addition because it is not installed in openshift-operators (currently the right place for all operators installed in AllNamespace mode) views of the installed operators in other namespaces in the OperatorHub do not show the RH Cert-Manager operator even though it has control in those namespaces.  My guess is that only operator installed in in the openshift-operators namespace are seen as as installed operator in every other namespace. Again this is misleading.

**Closed** 2024-05-12 00:01 UTC
Labels: lifecycle/rotten

**Comment by griffindvs** [comment] 2024-05-16 15:00
It does not look like this issue was resolved, and in a recent discussion with the Red Hat Cert Manager team I was under the impression a fix was in progress.

/reopen

/remove-lifecycle rotten

**Comment by leifmadsen** [comment] 2024-05-21 14:31
@griffindvs as this is affecting a productized component, I would suggest opening an issue at https://issues.redhat.com for tracking purposes. Issues in GitHub are generally not tracked as strongly.

Suggest starting at https://issues.redhat.com/projects/CM/summary
